language: python
os:
  - linux
  - osx
python:
  - 3.7
jobs:
  include:
    - os: osx
      osx_image: xcode11.3
  allow_failures:
    - os: osx
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create -f conda_env.yml
  - conda activate svm
  - pip install pytest-cov codecov
notifications:
  email: false
script:
  - pytest --cov=./
after_success:
  - codecov
